name: Echo Repository and Environment Variables

on:
  push:
    branches:
      - main

jobs:
  echo-vars:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: List all environment variables
        run: printenv
